In [1]:
#!/usr/bin/python

import json
import os
import re

import numpy as np
from scipy.stats import mode


### YOUR CODE HERE: write at least three functions which solve
### specific tasks by transforming the input x and returning the
### result. Name them according to the task ID as in the three
### examples below. Delete the three examples. The tasks you choose
### must be in the data/training directory, not data/evaluation.

# def solve_6a1e5592(x):
#     return x
#
#
# def solve_b2862040(x):
#     return x
#
#
# def solve_05269061(x):
#     return x


# def solve_045e512c(x):
#     # print( "Anshul " ,x)
#     val = mode([1,2,3,1,2,1,1,1,3,2,2,1])
#     print("val" , val.mode)
#     global data
#     data = x
#     return x

def solve_9f236235(x):
    data = x
    val_0_0 = data[0][0]
    best_grid = None

    for i in range(1, data.shape[0] + 1):

        temp_grid = np.array([[val_0_0] * i] * i)
        data_grid = data[:i , :i]

        if np.array_equal(temp_grid,data_grid):
            best_grid = tuple((i,i))        

    val = []
    for x in range(1, data.shape[0] + 1 , best_grid[0] + 1):
        _temp = []

        for y in range(1, data.shape[0] + 1, best_grid[0] + 1):
            _temp_val = data[x :x +  best_grid[0] -1  , y : y + best_grid[1] -1]
            _temp.append(_temp_val[0][0])    

        val.append(_temp)

    val = np.array(val)
    x = np.flip(val, 1)  
    
    return x

def main():
    # Find all the functions defined in this file whose names are
    # like solve_abcd1234(), and run them.

    # regex to match solve_* functions and extract task IDs
    p = r"solve_([a-f0-9]{8})"
    tasks_solvers = []
    # globals() gives a dict containing all global names (variables
    # and functions), as name: value pairs.
    for name in globals():
        m = re.match(p, name)
        if m:
            # if the name fits the pattern eg solve_abcd1234
            ID = m.group(1)  # just the task ID
            solve_fn = globals()[name]  # the fn itself
            tasks_solvers.append((ID, solve_fn))

    for ID, solve_fn in tasks_solvers:
        # for each task, read the data and call test()
        directory = os.path.join("..", "data", "training")
        json_filename = os.path.join(directory, ID + ".json")
        data = read_ARC_JSON(json_filename)
        test(ID, solve_fn, data)


def read_ARC_JSON(filepath):
    """Given a filepath, read in the ARC task data which is in JSON
    format. Extract the train/test input/output pairs of
    grids. Convert each grid to np.array and return train_input,
    train_output, test_input, test_output."""

    # Open the JSON file and load it 
    data = json.load(open(filepath))

    # Extract the train/test input/output grids. Each grid will be a
    # list of lists of ints. We convert to Numpy.
    train_input = [np.array(data['train'][i]['input']) for i in range(len(data['train']))]
    train_output = [np.array(data['train'][i]['output']) for i in range(len(data['train']))]
    test_input = [np.array(data['test'][i]['input']) for i in range(len(data['test']))]
    test_output = [np.array(data['test'][i]['output']) for i in range(len(data['test']))]

    return (train_input, train_output, test_input, test_output)


def test(taskID, solve, data):
    """Given a task ID, call the given solve() function on every
    example in the task data."""
    print(taskID)
    train_input, train_output, test_input, test_output = data
    print("Training grids")
    for x, y in zip(train_input, train_output):
        yhat = solve(x)
        show_result(x, y, yhat)
    print("Test grids")
    for x, y in zip(test_input, test_output):
        yhat = solve(x)
        show_result(x, y, yhat)


def show_result(x, y, yhat):
    print("Input")
    print(x)
    print("Correct output")
    print(y)
    print("Our output")
    print(yhat)
    print("Correct?")
    if y.shape != yhat.shape:
        print(f"False. Incorrect shape: {y.shape} v {yhat.shape}")
    else:
        print(np.all(y == yhat))


if __name__ == "__main__": main()


9f236235
Training grids
Input
[[3 3 3 3 2 0 0 0 0 2 0 0 0 0 2 0 0 0 0]
 [3 3 3 3 2 0 0 0 0 2 0 0 0 0 2 0 0 0 0]
 [3 3 3 3 2 0 0 0 0 2 0 0 0 0 2 0 0 0 0]
 [3 3 3 3 2 0 0 0 0 2 0 0 0 0 2 0 0 0 0]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [0 0 0 0 2 3 3 3 3 2 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 2 3 3 3 3 2 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 2 3 3 3 3 2 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 2 3 3 3 3 2 0 0 0 0 2 0 0 0 0]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [0 0 0 0 2 0 0 0 0 2 3 3 3 3 2 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 2 3 3 3 3 2 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 2 3 3 3 3 2 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 2 3 3 3 3 2 0 0 0 0]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 2 3 3 3 3 2 3 3 3 3 2 0 0 0 0]
 [3 3 3 3 2 3 3 3 3 2 3 3 3 3 2 0 0 0 0]
 [3 3 3 3 2 3 3 3 3 2 3 3 3 3 2 0 0 0 0]
 [3 3 3 3 2 3 3 3 3 2 3 3 3 3 2 0 0 0 0]]
Correct output
[[0 0 0 3]
 [0 0 3 0]
 [0 3 0 0]
 [0 3 3 3]]
Our output
[[0 0 0 3]
 [0 0 3 0]
 [0 3 0 0]
 [0 3 3 3]]
Correct?
True
Input
[[0 0 0 0 8 2 2 2 2 8 0 0 0 0 8 0 0 0 0]
 [0 0 0 0 8 2